/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login user.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Profile
         * @description Get current user profile.
         */
        get: operations["get_current_user_profile_api_v1_auth_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change Password
         * @description Change user password.
         */
        patch: operations["change_password_api_v1_auth_users_me_password_patch"];
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description List reports with filters.
         */
        get: operations["list_reports_api_v1_reports_get"];
        put?: never;
        /**
         * Create Report
         * @description Create report from raw text.
         */
        post: operations["create_report_api_v1_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/from-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Report From File
         * @description Create report from a PDF or DOCX file.
         */
        post: operations["create_report_from_file_api_v1_reports_from_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/from-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Report From Form
         * @description Create report from structured form. Skips LLM case extraction.
         */
        post: operations["create_report_from_form_api_v1_reports_from_form_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Get report details.
         */
        get: operations["get_report_api_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}/analysis-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Status
         * @description Get AI analysis status.
         */
        get: operations["get_analysis_status_api_v1_reports__report_id__analysis_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change Report Status
         * @description Change report status. Only specialists.
         */
        patch: operations["change_report_status_api_v1_reports__report_id__status_patch"];
        trace?: never;
    };
    "/api/v1/reports/{report_id}/specialist-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Specialist Review
         * @description Save specialist overrides.
         */
        patch: operations["specialist_review_api_v1_reports__report_id__specialist_review_patch"];
        trace?: never;
    };
    "/api/v1/reports/{report_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize Report
         * @description Finalize report. Only specialists.
         */
        post: operations["finalize_report_api_v1_reports__report_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}/reanalyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reanalyze Report
         * @description Re-analyze report with a different LLM provider/model.
         *     Only specialists can use this endpoint.
         *     This overwrites previous analysis results (Variant A - simple).
         */
        post: operations["reanalyze_report_api_v1_reports__report_id__reanalyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Drugs
         * @description Search drugs by name.
         */
        get: operations["search_drugs_api_v1_drugs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List all indexed documents.
         */
        get: operations["list_documents_api_v1_rag_documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description Upload drug's instruction manual (IMP) to RAG index.
         */
        post: operations["upload_document_api_v1_rag_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rag/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Delete document from RAG index.
         */
        delete: operations["delete_document_api_v1_rag_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIRecommendationsResponse */
        AIRecommendationsResponse: {
            /** Analysis Status */
            analysis_status: string;
            case_extraction?: components["schemas"]["ExtractedCaseData"] | null;
            /** Ime */
            ime?: {
                [key: string]: unknown;
            } | null;
            /** Naranjo */
            naranjo?: {
                [key: string]: unknown;
            } | null;
            /** Expectedness */
            expectedness?: {
                [key: string]: unknown;
            } | null;
            /** Completeness */
            completeness?: {
                [key: string]: unknown;
            } | null;
        };
        /** AdverseEffectFormData */
        AdverseEffectFormData: {
            /** Date */
            date?: string | null;
            /** Description */
            description: string;
            severity?: components["schemas"]["SeverityLevel"] | null;
            /** Is Serious */
            is_serious?: boolean | null;
            /** Outcome */
            outcome?: string | null;
            /** Causality Assessment */
            causality_assessment?: string | null;
        };
        /** AnalysisStatusResponse */
        AnalysisStatusResponse: {
            /** Analysis Status */
            analysis_status: string;
            /** Error */
            error?: string | null;
        };
        /** AuthResponse */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            user: components["schemas"]["UserResponse"];
        };
        /** Body_create_report_from_file_api_v1_reports_from_file_post */
        Body_create_report_from_file_api_v1_reports_from_file_post: {
            /** File */
            file: string;
        };
        /** Body_upload_document_api_v1_rag_documents_post */
        Body_upload_document_api_v1_rag_documents_post: {
            /** File */
            file: string;
            /** Drug Name Ru */
            drug_name_ru: string;
            /** Drug Name En */
            drug_name_en?: string;
            /** Atc Code */
            atc_code?: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** ChangeReportStatusRequest */
        ChangeReportStatusRequest: {
            /** Status */
            status: string;
            /** Comment */
            comment?: string | null;
        };
        /** CreateReportFromFormRequest */
        CreateReportFromFormRequest: {
            patient: components["schemas"]["PatientFormData"];
            doctor: components["schemas"]["DoctorFormData"];
            medication: components["schemas"]["MedicationFormData"];
            adverse_effect: components["schemas"]["AdverseEffectFormData"];
            additional_info: components["schemas"]["FilesFormData"];
        };
        /** CreateReportRequest */
        CreateReportRequest: {
            /** Raw Text */
            raw_text: string;
        };
        /**
         * DateRangeFilter
         * @enum {string}
         */
        DateRangeFilter: "today" | "week" | "month";
        /** DoctorFormData */
        DoctorFormData: {
            /** Name */
            name?: string | null;
            /** Specialty */
            specialty?: string | null;
            /** Organization */
            organization?: string | null;
            /** Email */
            email?: string | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Drug Name Ru */
            drug_name_ru: string;
            /** Status */
            status: string;
            /**
             * Indexed At
             * Format: date-time
             */
            indexed_at: string;
        };
        /** DrugResponse */
        DrugResponse: {
            /** Id */
            id?: string | null;
            /** Name Ru */
            name_ru: string;
            /** Name En */
            name_en?: string | null;
            /** Atc Code */
            atc_code?: string | null;
        };
        /** DrugSearchResponse */
        DrugSearchResponse: {
            /** Items */
            items: components["schemas"]["DrugResponse"][];
        };
        /** ExtractedCaseData */
        ExtractedCaseData: {
            /** Patient */
            patient?: {
                [key: string]: unknown;
            } | null;
            /** Reporter */
            reporter?: {
                [key: string]: unknown;
            } | null;
            /** Adverse Reaction */
            adverse_reaction?: {
                [key: string]: unknown;
            } | null;
            /** Suspect Drug */
            suspect_drug?: {
                [key: string]: unknown;
            } | null;
            /**
             * Concomitant Drugs
             * @default []
             */
            concomitant_drugs: {
                [key: string]: unknown;
            }[];
            /** Case Narrative */
            case_narrative?: string | null;
            /** Raw Text */
            raw_text?: string | null;
        };
        /** FilesFormData */
        FilesFormData: {
            /** Additional Info */
            additional_info?: string | null;
        };
        /** FinalizeReportResponse */
        FinalizeReportResponse: {
            /** Ok */
            ok: boolean;
            /**
             * Finalized At
             * Format: date-time
             */
            finalized_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MedicationFormData */
        MedicationFormData: {
            /** Trade Name */
            trade_name?: string | null;
            /** Inn */
            inn?: string | null;
            /** Dose */
            dose?: string | null;
            /** Route */
            route?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Indication */
            indication?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
        };
        /** PatientFormData */
        PatientFormData: {
            /** Name */
            name?: string | null;
            /** Age */
            age?: string | null;
            /** Sex */
            sex?: string | null;
            /** Weight */
            weight?: string | null;
            /** Diagnosis */
            diagnosis?: string | null;
            /** Comorbidities */
            comorbidities?: string | null;
        };
        /** ReanalyzeReportRequest */
        ReanalyzeReportRequest: {
            /**
             * Llm Provider
             * @description LLM provider: 'yandex' or 'ollama'
             */
            llm_provider: string;
            /**
             * Llm Model
             * @description Model name (e.g., 'gpt-4o-mini' for yandex, 'mistral' for ollama)
             */
            llm_model: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
        };
        /** ReportListResponse */
        ReportListResponse: {
            /** Items */
            items: components["schemas"]["ReportShortResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
        };
        /** ReportResponse */
        ReportResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ReportStatus"];
            /**
             * Reporter Id
             * Format: uuid
             */
            reporter_id: string;
            /** Raw Text */
            raw_text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            drug?: components["schemas"]["DrugResponse"] | null;
            extracted_data?: components["schemas"]["ExtractedCaseData"] | null;
            ai_recommendations: components["schemas"]["AIRecommendationsResponse"];
            /** Specialist Overrides */
            specialist_overrides?: {
                [key: string]: unknown;
            } | null;
        };
        /** ReportShortResponse */
        ReportShortResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ReportStatus"];
            /**
             * Reporter Id
             * Format: uuid
             */
            reporter_id: string;
            /** Drug Name */
            drug_name?: string | null;
            /** Adverse Reaction */
            adverse_reaction?: string | null;
            /** Reporter Name */
            reporter_name?: string | null;
            /** Is Clinically Significant */
            is_clinically_significant?: boolean | null;
            /** Analysis Status */
            analysis_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            severity?: components["schemas"]["SeverityLevel"] | null;
        };
        /**
         * ReportStatus
         * @enum {string}
         */
        ReportStatus: "submitted" | "clarification" | "analysis" | "finalized";
        /**
         * SeverityLevel
         * @enum {string}
         */
        SeverityLevel: "mild" | "moderate" | "severe" | "life-threatening";
        /** SimpleOkResponse */
        SimpleOkResponse: {
            /** Ok */
            ok: boolean;
        };
        /** SpecialistReviewRequest */
        SpecialistReviewRequest: {
            /** Causality */
            causality?: {
                [key: string]: string;
            } | null;
            /** Ime */
            ime?: {
                [key: string]: string;
            } | null;
            /** Naranjo */
            naranjo?: {
                [key: string]: string;
            } | null;
            /** Expectedness */
            expectedness?: {
                [key: string]: string;
            } | null;
            /** Completeness */
            completeness?: {
                [key: string]: string;
            } | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "reporter" | "specialist";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_profile_api_v1_auth_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    change_password_api_v1_auth_users_me_password_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_reports_get: {
        parameters: {
            query?: {
                status?: string | null;
                search?: string | null;
                severity?: components["schemas"]["SeverityLevel"] | null;
                date_range?: components["schemas"]["DateRangeFilter"] | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_v1_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_from_file_api_v1_reports_from_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_report_from_file_api_v1_reports_from_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_from_form_api_v1_reports_from_form_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportFromFormRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_status_api_v1_reports__report_id__analysis_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_report_status_api_v1_reports__report_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeReportStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    specialist_review_api_v1_reports__report_id__specialist_review_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialistReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_report_api_v1_reports__report_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reanalyze_report_api_v1_reports__report_id__reanalyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReanalyzeReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_drugs_api_v1_drugs_get: {
        parameters: {
            query: {
                search: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrugSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_rag_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
        };
    };
    upload_document_api_v1_rag_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_rag_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_rag_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
